config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'

  resources :loan_application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :pan_image,PanImageUploader
  mount_uploader :aadhar_image, AadharImageUploader
  mount_uploader :address_image, AddressImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home]

  def home
  end

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/loan_application_controller.rb
class LoanApplicationController < ApplicationController
  include Wicked::Wizard
  steps :personal, :company , :documents

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)

    render_wizard @user
  end

  private

  def user_params
    params.require(:user).permit(:name,:email, :pan_card ,:company_pan,:type_of_company , :annual_trunover, :funding_date,:pan_image,:aadhar_image,:address_image )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <p>#{sentence}</p>
    <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/loan_application_helper.rb
module LoanApplicationHelper
end

app/views/application/home.html.slim
= link_to("Apply for Loan", loan_application_path(:personal))

app/views/layouts/_navigation.html.slim
ul class="nav navbar-nav"
  li= link_to('<span class="glyphicon glyphicon-home"></span> Home'.html_safe, root_path)

ul class="nav navbar-nav navbar-right"
  - if current_user
    li= link_to('<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, edit_user_registration_path)
    li= link_to('<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, method: 'delete')
  - else
    li= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path)
    li= link_to('<span class="glyphicon glyphicon-saved"></span> Register'.html_safe, new_user_registration_path)

app/views/layouts/_notifications.html.slim
- if notice
  .alert.alert-info
    p= notice

- if alert
  .alert.alert-warning
    p= alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= content_for?(:title) ? yield(:title) + " - #{APPLICATION_NAME}" : "#{APPLICATION_NAME}" %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>

  </head>

  <body>
	  <nav class="navbar navbar-default">
		  <div class="container-fluid">
			  <div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed"
				          data-toggle="collapse" data-target="#menu-collapse">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
				  </button>
				  <%= link_to APPLICATION_NAME, root_path, class: 'navbar-brand' %>
			  </div>

			  <div class="collapse navbar-collapse" id="menu-collapse">

				  <%= render 'layouts/navigation' %>

			  </div>
		  </div>
	  </nav>

	  <div class="container">
		  <%= render 'layouts/notifications' %>

      <%= yield %>
	  </div>
  </body>
</html>

app/views/loan_application/_form.html.erb
<%= form_for @user, url: wizard_path do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit "Continue" %>
    or <%= link_to "skip this step", next_wizard_path %>
  </div>
<% end %>

app/views/loan_application/company.html.slim
.text-left
  h1 Company Details
= form_for @user, url: wizard_path do |f|
  - if @user.errors.any?
    .error_messages
      h2
        = pluralize(@user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :Companypan
    '
    = f.text_field :company_pan
  .field
    = f.label :Typeofcompany
    '
    = f.text_field :type_of_company
  .field
    = f.label :Annualtrunover
    '
    = f.text_field :annual_trunover
  .field
    = f.label :FoundingDate
    '
    = f.date_select :funding_date, start_year: 1900, end_year: Date.today.year, include_blank: true
  .actions
    = f.submit "Continue"

app/views/loan_application/documents.html.slim
.text-left
  h1 Documents Details

= form_for @user, url: wizard_path do |f|
  - if @user.errors.any?
    .error_messages
      h2
        = pluralize(@user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :UploadPanCard
    '
    = f.file_field :pan_image
  .field
    = f.label :AadharCard
    '
    = f.file_field :aadhar_image
  .field
    = f.label :AddressProof
    '
    = f.file_field :address_image
    '
  .actions
    = f.submit "Submit"

app/views/loan_application/personal.html.slim
.text-left
  h1 Personal Details

= form_for @user, url: wizard_path do |f|
  - if @user.errors.any?
    .error_messages
      h2
        = pluralize(@user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :Name
    '
    = f.text_field :name
  .field
    = f.label :PanCard
    '
    = f.text_field :pan_card
  .field
    = f.label :Email
    '
    = f.text_field :email
  .field
    = f.label :Mobile
    '
    = f.text_field :mobile
  .actions
    = f.submit "Continue"

app/views/loan_application/show.html.erb
fasa